apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
<<<<<<< HEAD
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
=======
  username: bW9uZ291c2Vy
  password: bW9uZ29wYXNzd29yZA==
>>>>>>> 0d30fb1985763d8c496b7de51fd1365aabf6eee5
