apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:  
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:  
            secretKeyRef: 
              name: mongo-secret
              key:  username
        - name: USER_PWD
          valueFrom:  
            secretKeyRef: 
              name: mongo-secret
<<<<<<< HEAD
              key:  password
=======
              key:  username
>>>>>>> 0d30fb1985763d8c496b7de51fd1365aabf6eee5
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key:  mongo-url
---
apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: webapp-service
=======
  name: mongo-service
>>>>>>> 0d30fb1985763d8c496b7de51fd1365aabf6eee5
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
<<<<<<< HEAD
      nodePort: 30100
=======
      nodePort: 30200
>>>>>>> 0d30fb1985763d8c496b7de51fd1365aabf6eee5
